# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pages-builder"
client_id = "13197c1c3fd2aca39c9036b71b5be751"
application_url = "https://plug-designs-cathedral-father.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://plug-designs-cathedral-father.trycloudflare.com/auth/callback",
  "https://plug-designs-cathedral-father.trycloudflare.com/auth/shopify/callback",
  "https://plug-designs-cathedral-father.trycloudflare.com/api/auth/callback",
  "https://plug-designs-cathedral-father.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ec0aaf8b.myshopify.com"
