# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Pagelab - Dev Room 17 (VM)"
client_id = "433d388883a2b917a3003803e5757178"
application_url = "https://washington-pix-oklahoma-harmony.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://washington-pix-oklahoma-harmony.trycloudflare.com/auth/callback",
  "https://washington-pix-oklahoma-harmony.trycloudflare.com/auth/shopify/callback",
  "https://washington-pix-oklahoma-harmony.trycloudflare.com/api/auth/callback",
  "https://washington-pix-oklahoma-harmony.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-room-17-mv-19-12-2023.myshopify.com"
