# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pages-builder"
client_id = "b559767290b67b4db00a3d213d55c281"
application_url = "https://testing-racing-nasdaq-classification.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://testing-racing-nasdaq-classification.trycloudflare.com/auth/callback",
  "https://testing-racing-nasdaq-classification.trycloudflare.com/auth/shopify/callback",
  "https://testing-racing-nasdaq-classification.trycloudflare.com/api/auth/callback",
  "https://testing-racing-nasdaq-classification.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test2r3.myshopify.com"
